name: Upload artifact
on:
  release:
    types: [published]
jobs:
  publish:
    name: Publish
    runs-on: macOS-10.14
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build portable_iblinter.zip
        run: make portable_zip
      - name: Upload portable_zip for Release assets
        run: ./script/upload_artifact.sh ./portable_iblinter.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Homebrew formula
        run: |
          brew tap $HOMEBREW_TAP_REPOSITORY
          pushd $(brew --repository)/Library/Taps/$HOMEBREW_TAP_REPOSITORY
          git config --local user.name "IBLinter Bot"
          git config --local user.email $GITHUB_ACTOR@users.noreply.github.com
          git remote set-url origin https://$GITHUB_ACTOR:$HOMEBREW_GITHUB_API_TOKEN@github.com/$HOMEBREW_TAP_REPOSITORY.git
          popd
          git checkout ${GITHUB_REF#refs/heads/}
          brew bump-formula-pr --tag=$(git describe --tags) --revision=$(git rev-parse HEAD) iblinter

          pushd $(brew --repository)/Library/Taps/$HOMEBREW_TAP_REPOSITORY
          FORMULA_PATH=iblinter.rb
          brew install $FORMULA_PATH --build-bottle
          brew bottle $FORMULA_PATH --force-core-tap

          BOTTLE=$(find . -name "*mojave.bottle.tar.gz")
          SHA256=$(shasum -a 256 $BOTTLE | cut -f1 -d ' ')
          ruby utils/replace_bottle_sha256.rb iblinter.rb $SHA256 mojave
          git commit -am"Update bottle sha256"
          git push origin HEAD

          $GITHUB_WORKSPACE/script/upload_artifact.sh $BOTTLE
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          HOMEBREW_NO_INSTALL_CLEANUP: 1
          HOMEBREW_TAP_REPOSITORY: IBDecodable/homebrew-tap
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update CocoaPods spec
        run: pod trunk push IBLinter.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          COCOAPODS_VALIDATOR_SKIP_XCODEBUILD: 1
