name: Cut new version
on:
  pull_request:
    branches:
      - release/*
jobs:
  cut_release:
    name: Cut new version
    runs-on: macOS-10.14
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Git config
        run: |
          git config --local user.name "IBLinter Bot"
          git config --local user.email $GITHUB_ACTOR@users.noreply.github.com
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag release version
        if: github.event.merged == true && github.event.pull_request.base.ref == 'master'
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/heads/release/}
          git checkout master
          git tag $RELEASE_VERSION
          git push origin --tags
