name: Publish new version
on: pull_request
jobs:
  publish:
    name: Publish
    runs-on: macOS-10.14
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Git config
        run: |
          git config --local user.name "IBLinter Bot"
          git config --local user.email $GITHUB_ACTOR@users.noreply.github.com
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Accept events only from release branch
        uses: actions/bin/filter@master
        with: { args: "branch release/*" }
      - name: Accept events only when release branch merged
        uses: actions/bin/filter@master
        with: { args: "merged true" }
      - name: Tag release version
        run: |
          RELEASE_VERSION=$(echo $GITHUB_REF | sed "s/release\///")
          git tag $RELEASE_VERSION
      - name: Push tag
        run: git push origin --tags
